version: '3.9'

services:
  java_app:
    container_name: java_app
    image: lab4-arsw-java-app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_DB:5432/blueprints
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_DB


  java_DB:
    container_name: java_DB
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blueprints
